apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limit-wallet-create
  annotations:
    kubernetes.io/ingress.class: kong
plugin: rate-limiting
config:
  minute: 1
  policy: local
  error_message: "Cannot create wallet in less than 1 minute per IP. Please try again later."