apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limit-global
  annotations:
    kubernetes.io/ingress.class: kong
plugin: rate-limiting
config:
  minute: 10
  policy: local
  error_message: "Cannot process your request due to system overload. Please try again later."