[package]
name = "pow-waf"
version = "0.1.0"
edition = "2021"

[build]
target = "wasm32-wasi"


[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
panic = "abort"
strip = "debuginfo"

[dependencies]
log = "0.4"
proxy-wasm = "0.2.2"
pin-project-lite = "0.2"
bytes = { version = "1.7"}
http = { version = "0.2" }
mime_guess = { version = "2.0" }
# reqwest = { version = "*" }
hyper = { version = "0.14", features = ["client", "http1"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "2.4"
tower-service = "0.3"
tokio = { version = "1.39.3" }

# calloop = { version = "0.14", features = ["executor"] }
# winit = { version = "0.30" }

