whitelist:
  - "46.3.240.0/24"
  - "2001:db8::/32"
virtual_hosts:
  - host: "example.com"
    routes:
      - path: "/"
        rate_limit:
          unit: minute
          requests_per_unit: 100
      - path: "/api"
        rate_limit:
          unit: minute
          requests_per_unit: 50
        children:
          - path: "/users"
            rate_limit:
                unit: minute
                requests_per_unit: 100
          - path: "/posts/*"
            rate_limit:
                unit: minute
                requests_per_unit: 100
  - host: "another-example.com"
    routes:
      - path: "/"
        rate_limit:
          unit: minute
          requests_per_unit: 200
      - path: "/about"
        rate_limit:
          unit: minute
          requests_per_unit: 100