apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: istio
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wallet-create-istio
  annotations: []
spec:
  parentRefs:
  - name: istio
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /wallet
    backendRefs:
    - name: echo
      kind: Service
      port: 1027
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: list-assets-istio
  annotations: []
spec:
  parentRefs:
  - name: istio
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /assets
    backendRefs:
    - name: echo
      kind: Service
      port: 1027