resources:
- kong.crd.yaml
- namespace.yaml
helmCharts:
- name: ingress
  namespace: kong
  releaseName: gate
  version: 0.13.1
  repo: https://charts.konghq.com
  includeCRDs: false
  valuesFile: ingress.values.yaml
  apiVersions:
  - gateway.networking.k8s.io/v1